version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: flask_backend_todo
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-frontend-todo
    ports:
      - "5173:5173"
    depends_on:
      - backend
  
  test:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: flask_backend_tests
    command: pytest 
    depends_on:
      - backend